export enum ScreenKeys {
  HOME = 'HOME',
  SEASON = 'SEASON',
  TEAM = 'TEAM',
  TEAM_ROSTER = 'TEAM_ROSTER',
  SUBSTITUTE_PLAYER = 'SUBSTITUTE_PLAYER',
  PLAYER_DRILLDOWN = 'PLAYER_DRILLDOWN',
  VIEW_LINEUPS = 'VIEW_LINEUPS',
  DRAFT_PROSPECTS = 'DRAFT_PROSPECTS',
  DRAFT = 'DRAFT',
  FRONT_OFFICE = 'FRONT_OFFICE',
  CONTRACTS = 'CONTRACTS',
  CONTRACT_DRILLDOWN = 'CONTRACT_DRILLDOWN',
  PLAYOFFS = 'PLAYOFFS',
  TRADES = 'TRADES',
}

export enum PostRoundScreenKeys {
  TEAM_STATS = 'TEAM_STATS',
  PLAYER_STATS = 'PLAYER_STATS',
  PLAYER_EXP = 'PLAYER_EXP',
}
