export enum ScreenKeys {
  HOME = 'HOME',
  SEASON = 'SEASON',
  TEAM = 'TEAM',
  TEAM_ROSTER = 'TEAM_ROSTER',
  SUBSTITUTE_PLAYER = 'SUBSTITUTE_PLAYER',
  PLAYER_DRILLDOWN = 'PLAYER_DRILLDOWN',
  VIEW_LINEUPS = 'VIEW_LINEUPS',
  DRAFT_PROSPECTS = 'DRAFT_PROSPECTS',
  DRAFT = 'DRAFT',
}

export enum PostRoundScreenKeys {
  TEAM_STATS = 'TEAM_STATS',
  PLAYER_STATS = 'PLAYER_STATS',
  PLAYER_EXP = 'PLAYER_EXP',
}
